require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe BandPhotoAttachmentsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # BandPhotoAttachment. As you add validations to BandPhotoAttachment, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BandPhotoAttachmentsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all band_photo_attachments as @band_photo_attachments" do
      band_photo_attachment = BandPhotoAttachment.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:band_photo_attachments)).to eq([band_photo_attachment])
    end
  end

  describe "GET #show" do
    it "assigns the requested band_photo_attachment as @band_photo_attachment" do
      band_photo_attachment = BandPhotoAttachment.create! valid_attributes
      get :show, {:id => band_photo_attachment.to_param}, valid_session
      expect(assigns(:band_photo_attachment)).to eq(band_photo_attachment)
    end
  end

  describe "GET #new" do
    it "assigns a new band_photo_attachment as @band_photo_attachment" do
      get :new, {}, valid_session
      expect(assigns(:band_photo_attachment)).to be_a_new(BandPhotoAttachment)
    end
  end

  describe "GET #edit" do
    it "assigns the requested band_photo_attachment as @band_photo_attachment" do
      band_photo_attachment = BandPhotoAttachment.create! valid_attributes
      get :edit, {:id => band_photo_attachment.to_param}, valid_session
      expect(assigns(:band_photo_attachment)).to eq(band_photo_attachment)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new BandPhotoAttachment" do
        expect {
          post :create, {:band_photo_attachment => valid_attributes}, valid_session
        }.to change(BandPhotoAttachment, :count).by(1)
      end

      it "assigns a newly created band_photo_attachment as @band_photo_attachment" do
        post :create, {:band_photo_attachment => valid_attributes}, valid_session
        expect(assigns(:band_photo_attachment)).to be_a(BandPhotoAttachment)
        expect(assigns(:band_photo_attachment)).to be_persisted
      end

      it "redirects to the created band_photo_attachment" do
        post :create, {:band_photo_attachment => valid_attributes}, valid_session
        expect(response).to redirect_to(BandPhotoAttachment.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved band_photo_attachment as @band_photo_attachment" do
        post :create, {:band_photo_attachment => invalid_attributes}, valid_session
        expect(assigns(:band_photo_attachment)).to be_a_new(BandPhotoAttachment)
      end

      it "re-renders the 'new' template" do
        post :create, {:band_photo_attachment => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested band_photo_attachment" do
        band_photo_attachment = BandPhotoAttachment.create! valid_attributes
        put :update, {:id => band_photo_attachment.to_param, :band_photo_attachment => new_attributes}, valid_session
        band_photo_attachment.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested band_photo_attachment as @band_photo_attachment" do
        band_photo_attachment = BandPhotoAttachment.create! valid_attributes
        put :update, {:id => band_photo_attachment.to_param, :band_photo_attachment => valid_attributes}, valid_session
        expect(assigns(:band_photo_attachment)).to eq(band_photo_attachment)
      end

      it "redirects to the band_photo_attachment" do
        band_photo_attachment = BandPhotoAttachment.create! valid_attributes
        put :update, {:id => band_photo_attachment.to_param, :band_photo_attachment => valid_attributes}, valid_session
        expect(response).to redirect_to(band_photo_attachment)
      end
    end

    context "with invalid params" do
      it "assigns the band_photo_attachment as @band_photo_attachment" do
        band_photo_attachment = BandPhotoAttachment.create! valid_attributes
        put :update, {:id => band_photo_attachment.to_param, :band_photo_attachment => invalid_attributes}, valid_session
        expect(assigns(:band_photo_attachment)).to eq(band_photo_attachment)
      end

      it "re-renders the 'edit' template" do
        band_photo_attachment = BandPhotoAttachment.create! valid_attributes
        put :update, {:id => band_photo_attachment.to_param, :band_photo_attachment => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested band_photo_attachment" do
      band_photo_attachment = BandPhotoAttachment.create! valid_attributes
      expect {
        delete :destroy, {:id => band_photo_attachment.to_param}, valid_session
      }.to change(BandPhotoAttachment, :count).by(-1)
    end

    it "redirects to the band_photo_attachments list" do
      band_photo_attachment = BandPhotoAttachment.create! valid_attributes
      delete :destroy, {:id => band_photo_attachment.to_param}, valid_session
      expect(response).to redirect_to(band_photo_attachments_url)
    end
  end

end
